//
//  DKDocumentDummy.swift
//  search_blog_and_cafeTests
//
//  Created by Bo-Young PARK on 2020/02/25.
//  Copyright © 2020 Boyoung Park. All rights reserved.
//

import Foundation
@testable import search_blog_and_cafe

extension DKBlogDummy {
    struct DKDocumentDummy {
        let blogDoc0 = DKDocument(title: "Gymnastic Champion Step3 Jisu Na - SU Education Tauranga", contents: "JIsu had a great year 2019. There were 5 competitions in New Zealand for gymnastics step 3 in 2019. Taupo competition, Rotorura competition, Hamilton competition, Tauranga competition and Midland Championship competition. Jisu won all 5 competitions this year. Well done <b>Jisu</b>!!! 2019년 뉴질랜드...", url: URL(string: "http://sueducation.tistory.com/5"), cafeName: nil, blogName: "SU Education", thumbnailURL: URL(string: "http://sueducation.tistory.com/5"), datetime: Date.from(dateString: "2019-12-31T06:00:00.000+09:00"))
        let blogDoc1 = DKDocument(title: "HAPPEE BIRTHDAE JISU", contents: "정말 정말 행복했던 나의 열여덟번 째 생일 20190910 20190918 이 외에도 생일 축하해준 사람 다 고마워 ♥️ ♥️", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=kimjisu0918&logNo=221655971132"), cafeName: nil, blogName: "｡ﾟ.*♥·˚ ｡:°♡*  ✉︎ ˖⁺⑅", thumbnailURL: URL(string: "https://search3.kakaocdn.net/argon/130x130_85_c/5jk9he4Jk1M"), datetime: Date.from(dateString: "2019-09-22T18:37:00.000+09:00"))
        let blogDoc2 = DKDocument(title: "Ha(jisu)ppiness,", contents: "나는 참 한결같은 취향이다. 이건너무 신박하고 귀엽기도하고 맛있는 생일추카 하지웅씨와의 힐링타임 해리포터 보면서 중국음식먹기 오빠 참 잘뒀다 나는 실력이 나이에 반비례 해지는가.. 월남쌈은 너무 행복한 쌈이다. 한쌈가득 몽땅 내가좋아하는거 엄마랑 카페데이트 진짜 오랜만에 들어본 내 별명 코스트코에가면...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=hajisu1004&logNo=221698212511"), cafeName: nil, blogName: "Haayam.", thumbnailURL: URL(string: "https://search4.kakaocdn.net/argon/130x130_85_c/7JWqh6uF8SY"), datetime: Date.from(dateString: "2019-11-05T01:52:00.000+09:00"))
        let blogDoc3 = DKDocument(title: "THANKS, JISU. 🤟💙🥺", contents: "2019.02.11. 결혼 한 지슝이네 집에 놀러 갔던 날, 신나게 받아 온 선물 꾸러미들. 작은거라고 별거없다고 했지만 하나 하나 나를 생각하면서 샀을 너가 눈에 보이는데 이게 작을 수가 없지요. 그리고 작기에는 크다. 지슝앜ㅋㅋㅋ 크나 큰 선물 너무 감사합니다. (신혼여행 하와이 선물!) ’전체샷’ 알로하~~~ 이렇게...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=annau__u&logNo=221465137276"), cafeName: nil, blogName: "SIEMPRE DOMINGO", thumbnailURL: URL(string: "https://search3.kakaocdn.net/argon/130x130_85_c/5w0ebTPddwV"), datetime: Date.from(dateString: "2019-02-13T21:12:00.000+09:00"))
        let blogDoc4 = DKDocument(title: "Jisu's WH, 2020 영국 청년교류제도(YMS) 합격", contents: "선발자들에게만 오는 메일 ​ 2020년 2월 12일 오전 11시 36분, 밥 먹다가 오픈채팅방이 난리가 나서 메일 확인을 해보니 선발되었다. 메일을 받지 못했다는 사람이 수두룩한데 정말 감사한 일이다. 오늘 일어나서 메일함 새로고침을 얼마나 했던지... 작년보다 경쟁률이 훨씬 높아졌기에 긴장했었는데 붙어서 정말 행복...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=jisuver&logNo=221806025820"), cafeName: nil, blogName: "Jisulog", thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/DpOIAK426nr"), datetime: Date.from(dateString: "2020-02-12T14:16:00.000+09:00"))
        let blogDoc5 = DKDocument(title: "Gymnastic Champion Step3 Jisu Na - SU Education Tauranga", contents: "JIsu had a great year 2019. There were 5 competitions in New Zealand for gymnastics step 3 in 2019. Taupo competition, Rotorura competition, Hamilton competition, Tauranga competition and Midland Championship competition. Jisu won all 5 competitions this year. Well done <b>Jisu</b>!!! 2019년 뉴질랜드...", url: URL(string: "http://sueducation.tistory.com/5"), cafeName: nil, blogName: "SU Education", thumbnailURL: URL(string: "http://sueducation.tistory.com/5"), datetime: Date.from(dateString: "2019-12-31T06:00:00.000+09:00"))
        let blogDoc6 = DKDocument(title: "HAPPEE BIRTHDAE JISU", contents: "정말 정말 행복했던 나의 열여덟번 째 생일 20190910 20190918 이 외에도 생일 축하해준 사람 다 고마워 ♥️ ♥️", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=kimjisu0918&logNo=221655971132"), cafeName: nil, blogName: "｡ﾟ.*♥·˚ ｡:°♡*  ✉︎ ˖⁺⑅", thumbnailURL: URL(string: "https://search3.kakaocdn.net/argon/130x130_85_c/5jk9he4Jk1M"), datetime: Date.from(dateString: "2019-09-22T18:37:00.000+09:00"))
        let blogDoc7 = DKDocument(title: "Ha(jisu)ppiness,", contents: "나는 참 한결같은 취향이다. 이건너무 신박하고 귀엽기도하고 맛있는 생일추카 하지웅씨와의 힐링타임 해리포터 보면서 중국음식먹기 오빠 참 잘뒀다 나는 실력이 나이에 반비례 해지는가.. 월남쌈은 너무 행복한 쌈이다. 한쌈가득 몽땅 내가좋아하는거 엄마랑 카페데이트 진짜 오랜만에 들어본 내 별명 코스트코에가면...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=hajisu1004&logNo=221698212511"), cafeName: nil, blogName: "Haayam.", thumbnailURL: URL(string: "https://search4.kakaocdn.net/argon/130x130_85_c/7JWqh6uF8SY"), datetime: Date.from(dateString: "2019-11-05T01:52:00.000+09:00"))
        let blogDoc8 = DKDocument(title: "THANKS, JISU. 🤟💙🥺", contents: "2019.02.11. 결혼 한 지슝이네 집에 놀러 갔던 날, 신나게 받아 온 선물 꾸러미들. 작은거라고 별거없다고 했지만 하나 하나 나를 생각하면서 샀을 너가 눈에 보이는데 이게 작을 수가 없지요. 그리고 작기에는 크다. 지슝앜ㅋㅋㅋ 크나 큰 선물 너무 감사합니다. (신혼여행 하와이 선물!) ’전체샷’ 알로하~~~ 이렇게...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=annau__u&logNo=221465137276"), cafeName: nil, blogName: "SIEMPRE DOMINGO", thumbnailURL: URL(string: "https://search3.kakaocdn.net/argon/130x130_85_c/5w0ebTPddwV"), datetime: Date.from(dateString: "2019-02-13T21:12:00.000+09:00"))
        let blogDoc9 = DKDocument(title: "Jisu's WH, 2020 영국 청년교류제도(YMS) 합격", contents: "선발자들에게만 오는 메일 ​ 2020년 2월 12일 오전 11시 36분, 밥 먹다가 오픈채팅방이 난리가 나서 메일 확인을 해보니 선발되었다. 메일을 받지 못했다는 사람이 수두룩한데 정말 감사한 일이다. 오늘 일어나서 메일함 새로고침을 얼마나 했던지... 작년보다 경쟁률이 훨씬 높아졌기에 긴장했었는데 붙어서 정말 행복...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=jisuver&logNo=221806025820"), cafeName: nil, blogName: "Jisulog", thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/DpOIAK426nr"), datetime: Date.from(dateString: "2020-02-12T14:16:00.000+09:00"))
        let blogDoc10 = DKDocument(title: "Gymnastic Champion Step3 Jisu Na - SU Education Tauranga", contents: "JIsu had a great year 2019. There were 5 competitions in New Zealand for gymnastics step 3 in 2019. Taupo competition, Rotorura competition, Hamilton competition, Tauranga competition and Midland Championship competition. Jisu won all 5 competitions this year. Well done <b>Jisu</b>!!! 2019년 뉴질랜드...", url: URL(string: "http://sueducation.tistory.com/5"), cafeName: nil, blogName: "SU Education", thumbnailURL: URL(string: "http://sueducation.tistory.com/5"), datetime: Date.from(dateString: "2019-12-31T06:00:00.000+09:00"))
        let blogDoc11 = DKDocument(title: "HAPPEE BIRTHDAE JISU", contents: "정말 정말 행복했던 나의 열여덟번 째 생일 20190910 20190918 이 외에도 생일 축하해준 사람 다 고마워 ♥️ ♥️", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=kimjisu0918&logNo=221655971132"), cafeName: nil, blogName: "｡ﾟ.*♥·˚ ｡:°♡*  ✉︎ ˖⁺⑅", thumbnailURL: URL(string: "https://search3.kakaocdn.net/argon/130x130_85_c/5jk9he4Jk1M"), datetime: Date.from(dateString: "2019-09-22T18:37:00.000+09:00"))
        let blogDoc12 = DKDocument(title: "Ha(jisu)ppiness,", contents: "나는 참 한결같은 취향이다. 이건너무 신박하고 귀엽기도하고 맛있는 생일추카 하지웅씨와의 힐링타임 해리포터 보면서 중국음식먹기 오빠 참 잘뒀다 나는 실력이 나이에 반비례 해지는가.. 월남쌈은 너무 행복한 쌈이다. 한쌈가득 몽땅 내가좋아하는거 엄마랑 카페데이트 진짜 오랜만에 들어본 내 별명 코스트코에가면...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=hajisu1004&logNo=221698212511"), cafeName: nil, blogName: "Haayam.", thumbnailURL: URL(string: "https://search4.kakaocdn.net/argon/130x130_85_c/7JWqh6uF8SY"), datetime: Date.from(dateString: "2019-11-05T01:52:00.000+09:00"))
        let blogDoc13 = DKDocument(title: "THANKS, JISU. 🤟💙🥺", contents: "2019.02.11. 결혼 한 지슝이네 집에 놀러 갔던 날, 신나게 받아 온 선물 꾸러미들. 작은거라고 별거없다고 했지만 하나 하나 나를 생각하면서 샀을 너가 눈에 보이는데 이게 작을 수가 없지요. 그리고 작기에는 크다. 지슝앜ㅋㅋㅋ 크나 큰 선물 너무 감사합니다. (신혼여행 하와이 선물!) ’전체샷’ 알로하~~~ 이렇게...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=annau__u&logNo=221465137276"), cafeName: nil, blogName: "SIEMPRE DOMINGO", thumbnailURL: URL(string: "https://search3.kakaocdn.net/argon/130x130_85_c/5w0ebTPddwV"), datetime: Date.from(dateString: "2019-02-13T21:12:00.000+09:00"))
        let blogDoc14 = DKDocument(title: "Jisu's WH, 2020 영국 청년교류제도(YMS) 합격", contents: "선발자들에게만 오는 메일 ​ 2020년 2월 12일 오전 11시 36분, 밥 먹다가 오픈채팅방이 난리가 나서 메일 확인을 해보니 선발되었다. 메일을 받지 못했다는 사람이 수두룩한데 정말 감사한 일이다. 오늘 일어나서 메일함 새로고침을 얼마나 했던지... 작년보다 경쟁률이 훨씬 높아졌기에 긴장했었는데 붙어서 정말 행복...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=jisuver&logNo=221806025820"), cafeName: nil, blogName: "Jisulog", thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/DpOIAK426nr"), datetime: Date.from(dateString: "2020-02-12T14:16:00.000+09:00"))
        let blogDoc15 = DKDocument(title: "Gymnastic Champion Step3 Jisu Na - SU Education Tauranga", contents: "JIsu had a great year 2019. There were 5 competitions in New Zealand for gymnastics step 3 in 2019. Taupo competition, Rotorura competition, Hamilton competition, Tauranga competition and Midland Championship competition. Jisu won all 5 competitions this year. Well done <b>Jisu</b>!!! 2019년 뉴질랜드...", url: URL(string: "http://sueducation.tistory.com/5"), cafeName: nil, blogName: "SU Education", thumbnailURL: URL(string: "http://sueducation.tistory.com/5"), datetime: Date.from(dateString: "2019-12-31T06:00:00.000+09:00"))
        let blogDoc16 = DKDocument(title: "HAPPEE BIRTHDAE JISU", contents: "정말 정말 행복했던 나의 열여덟번 째 생일 20190910 20190918 이 외에도 생일 축하해준 사람 다 고마워 ♥️ ♥️", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=kimjisu0918&logNo=221655971132"), cafeName: nil, blogName: "｡ﾟ.*♥·˚ ｡:°♡*  ✉︎ ˖⁺⑅", thumbnailURL: URL(string: "https://search3.kakaocdn.net/argon/130x130_85_c/5jk9he4Jk1M"), datetime: Date.from(dateString: "2019-09-22T18:37:00.000+09:00"))
        let blogDoc17 = DKDocument(title: "Ha(jisu)ppiness,", contents: "나는 참 한결같은 취향이다. 이건너무 신박하고 귀엽기도하고 맛있는 생일추카 하지웅씨와의 힐링타임 해리포터 보면서 중국음식먹기 오빠 참 잘뒀다 나는 실력이 나이에 반비례 해지는가.. 월남쌈은 너무 행복한 쌈이다. 한쌈가득 몽땅 내가좋아하는거 엄마랑 카페데이트 진짜 오랜만에 들어본 내 별명 코스트코에가면...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=hajisu1004&logNo=221698212511"), cafeName: nil, blogName: "Haayam.", thumbnailURL: URL(string: "https://search4.kakaocdn.net/argon/130x130_85_c/7JWqh6uF8SY"), datetime: Date.from(dateString: "2019-11-05T01:52:00.000+09:00"))
        let blogDoc18 = DKDocument(title: "THANKS, JISU. 🤟💙🥺", contents: "2019.02.11. 결혼 한 지슝이네 집에 놀러 갔던 날, 신나게 받아 온 선물 꾸러미들. 작은거라고 별거없다고 했지만 하나 하나 나를 생각하면서 샀을 너가 눈에 보이는데 이게 작을 수가 없지요. 그리고 작기에는 크다. 지슝앜ㅋㅋㅋ 크나 큰 선물 너무 감사합니다. (신혼여행 하와이 선물!) ’전체샷’ 알로하~~~ 이렇게...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=annau__u&logNo=221465137276"), cafeName: nil, blogName: "SIEMPRE DOMINGO", thumbnailURL: URL(string: "https://search3.kakaocdn.net/argon/130x130_85_c/5w0ebTPddwV"), datetime: Date.from(dateString: "2019-02-13T21:12:00.000+09:00"))
        let blogDoc19 = DKDocument(title: "Jisu's WH, 2020 영국 청년교류제도(YMS) 합격", contents: "선발자들에게만 오는 메일 ​ 2020년 2월 12일 오전 11시 36분, 밥 먹다가 오픈채팅방이 난리가 나서 메일 확인을 해보니 선발되었다. 메일을 받지 못했다는 사람이 수두룩한데 정말 감사한 일이다. 오늘 일어나서 메일함 새로고침을 얼마나 했던지... 작년보다 경쟁률이 훨씬 높아졌기에 긴장했었는데 붙어서 정말 행복...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=jisuver&logNo=221806025820"), cafeName: nil, blogName: "Jisulog", thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/DpOIAK426nr"), datetime: Date.from(dateString: "2020-02-12T14:16:00.000+09:00"))
        let blogDoc20 = DKDocument(title: "Gymnastic Champion Step3 Jisu Na - SU Education Tauranga", contents: "JIsu had a great year 2019. There were 5 competitions in New Zealand for gymnastics step 3 in 2019. Taupo competition, Rotorura competition, Hamilton competition, Tauranga competition and Midland Championship competition. Jisu won all 5 competitions this year. Well done <b>Jisu</b>!!! 2019년 뉴질랜드...", url: URL(string: "http://sueducation.tistory.com/5"), cafeName: nil, blogName: "SU Education", thumbnailURL: URL(string: "http://sueducation.tistory.com/5"), datetime: Date.from(dateString: "2019-12-31T06:00:00.000+09:00"))
        let blogDoc21 = DKDocument(title: "HAPPEE BIRTHDAE JISU", contents: "정말 정말 행복했던 나의 열여덟번 째 생일 20190910 20190918 이 외에도 생일 축하해준 사람 다 고마워 ♥️ ♥️", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=kimjisu0918&logNo=221655971132"), cafeName: nil, blogName: "｡ﾟ.*♥·˚ ｡:°♡*  ✉︎ ˖⁺⑅", thumbnailURL: URL(string: "https://search3.kakaocdn.net/argon/130x130_85_c/5jk9he4Jk1M"), datetime: Date.from(dateString: "2019-09-22T18:37:00.000+09:00"))
        let blogDoc22 = DKDocument(title: "Ha(jisu)ppiness,", contents: "나는 참 한결같은 취향이다. 이건너무 신박하고 귀엽기도하고 맛있는 생일추카 하지웅씨와의 힐링타임 해리포터 보면서 중국음식먹기 오빠 참 잘뒀다 나는 실력이 나이에 반비례 해지는가.. 월남쌈은 너무 행복한 쌈이다. 한쌈가득 몽땅 내가좋아하는거 엄마랑 카페데이트 진짜 오랜만에 들어본 내 별명 코스트코에가면...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=hajisu1004&logNo=221698212511"), cafeName: nil, blogName: "Haayam.", thumbnailURL: URL(string: "https://search4.kakaocdn.net/argon/130x130_85_c/7JWqh6uF8SY"), datetime: Date.from(dateString: "2019-11-05T01:52:00.000+09:00"))
        let blogDoc23 = DKDocument(title: "THANKS, JISU. 🤟💙🥺", contents: "2019.02.11. 결혼 한 지슝이네 집에 놀러 갔던 날, 신나게 받아 온 선물 꾸러미들. 작은거라고 별거없다고 했지만 하나 하나 나를 생각하면서 샀을 너가 눈에 보이는데 이게 작을 수가 없지요. 그리고 작기에는 크다. 지슝앜ㅋㅋㅋ 크나 큰 선물 너무 감사합니다. (신혼여행 하와이 선물!) ’전체샷’ 알로하~~~ 이렇게...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=annau__u&logNo=221465137276"), cafeName: nil, blogName: "SIEMPRE DOMINGO", thumbnailURL: URL(string: "https://search3.kakaocdn.net/argon/130x130_85_c/5w0ebTPddwV"), datetime: Date.from(dateString: "2019-02-13T21:12:00.000+09:00"))
        let blogDoc24 = DKDocument(title: "Jisu's WH, 2020 영국 청년교류제도(YMS) 합격", contents: "선발자들에게만 오는 메일 ​ 2020년 2월 12일 오전 11시 36분, 밥 먹다가 오픈채팅방이 난리가 나서 메일 확인을 해보니 선발되었다. 메일을 받지 못했다는 사람이 수두룩한데 정말 감사한 일이다. 오늘 일어나서 메일함 새로고침을 얼마나 했던지... 작년보다 경쟁률이 훨씬 높아졌기에 긴장했었는데 붙어서 정말 행복...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=jisuver&logNo=221806025820"), cafeName: nil, blogName: "Jisulog", thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/DpOIAK426nr"), datetime: Date.from(dateString: "2020-02-12T14:16:00.000+09:00"))
        let blogDoc25 = DKDocument(title: "Gymnastic Champion Step3 Jisu Na - SU Education Tauranga", contents: "JIsu had a great year 2019. There were 5 competitions in New Zealand for gymnastics step 3 in 2019. Taupo competition, Rotorura competition, Hamilton competition, Tauranga competition and Midland Championship competition. Jisu won all 5 competitions this year. Well done <b>Jisu</b>!!! 2019년 뉴질랜드...", url: URL(string: "http://sueducation.tistory.com/5"), cafeName: nil, blogName: "SU Education", thumbnailURL: URL(string: "http://sueducation.tistory.com/5"), datetime: Date.from(dateString: "2019-12-31T06:00:00.000+09:00"))
        let blogDoc26 = DKDocument(title: "HAPPEE BIRTHDAE JISU", contents: "정말 정말 행복했던 나의 열여덟번 째 생일 20190910 20190918 이 외에도 생일 축하해준 사람 다 고마워 ♥️ ♥️", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=kimjisu0918&logNo=221655971132"), cafeName: nil, blogName: "｡ﾟ.*♥·˚ ｡:°♡*  ✉︎ ˖⁺⑅", thumbnailURL: URL(string: "https://search3.kakaocdn.net/argon/130x130_85_c/5jk9he4Jk1M"), datetime: Date.from(dateString: "2019-09-22T18:37:00.000+09:00"))
        let blogDoc27 = DKDocument(title: "Ha(jisu)ppiness,", contents: "나는 참 한결같은 취향이다. 이건너무 신박하고 귀엽기도하고 맛있는 생일추카 하지웅씨와의 힐링타임 해리포터 보면서 중국음식먹기 오빠 참 잘뒀다 나는 실력이 나이에 반비례 해지는가.. 월남쌈은 너무 행복한 쌈이다. 한쌈가득 몽땅 내가좋아하는거 엄마랑 카페데이트 진짜 오랜만에 들어본 내 별명 코스트코에가면...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=hajisu1004&logNo=221698212511"), cafeName: nil, blogName: "Haayam.", thumbnailURL: URL(string: "https://search4.kakaocdn.net/argon/130x130_85_c/7JWqh6uF8SY"), datetime: Date.from(dateString: "2019-11-05T01:52:00.000+09:00"))
        let blogDoc28 = DKDocument(title: "THANKS, JISU. 🤟💙🥺", contents: "2019.02.11. 결혼 한 지슝이네 집에 놀러 갔던 날, 신나게 받아 온 선물 꾸러미들. 작은거라고 별거없다고 했지만 하나 하나 나를 생각하면서 샀을 너가 눈에 보이는데 이게 작을 수가 없지요. 그리고 작기에는 크다. 지슝앜ㅋㅋㅋ 크나 큰 선물 너무 감사합니다. (신혼여행 하와이 선물!) ’전체샷’ 알로하~~~ 이렇게...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=annau__u&logNo=221465137276"), cafeName: nil, blogName: "SIEMPRE DOMINGO", thumbnailURL: URL(string: "https://search3.kakaocdn.net/argon/130x130_85_c/5w0ebTPddwV"), datetime: Date.from(dateString: "2019-02-13T21:12:00.000+09:00"))
        let blogDoc29 = DKDocument(title: "Jisu's WH, 2020 영국 청년교류제도(YMS) 합격", contents: "선발자들에게만 오는 메일 ​ 2020년 2월 12일 오전 11시 36분, 밥 먹다가 오픈채팅방이 난리가 나서 메일 확인을 해보니 선발되었다. 메일을 받지 못했다는 사람이 수두룩한데 정말 감사한 일이다. 오늘 일어나서 메일함 새로고침을 얼마나 했던지... 작년보다 경쟁률이 훨씬 높아졌기에 긴장했었는데 붙어서 정말 행복...", url: URL(string: "http://blog.naver.com/PostView.nhn?blogId=jisuver&logNo=221806025820"), cafeName: nil, blogName: "Jisulog", thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/DpOIAK426nr"), datetime: Date.from(dateString: "2020-02-12T14:16:00.000+09:00"))
    }
}

extension DKCafeDummy {
    struct DKDocumentDummy {
        let cafeDoc0 = DKDocument(title: "letter Happy day", contents: "take this chance and show your best. I hope you&#39;ll always be sincere with us, jisu. support is important to you now, so I will try to show you my love as...", url: URL(string: "http://cafe.daum.net/too.official/r7fI/6607"), cafeName: "TOO 공식팬카페", blogName: nil, thumbnailURL: nil, datetime: Date.from(dateString: "2020-01-19T10:03:15.000+09:00"))
        let cafeDoc1 = DKDocument(title: "Jisu Kim 가입신청서", contents: "CK처리에 동의하십니까? 네 -IC Information - 1. 캐릭터 닉네임을 기입해 주세요. Jisu_Kim 2. 자신의 캐릭터 생김새와 성향, 성격(컨셉)에 대해 적어주세요. 한국...", url: URL(string: "http://cafe.daum.net/tgfyc/Y5us/3"), cafeName: "やみの かだん", blogName: nil, thumbnailURL: URL(string: "https://search1.kakaocdn.net/thumb/P100x100/?fname=https%3A%2F%2Fsearch3.kakaocdn.net%2Fargon%2F130x130_85_c%2F6Yk4pzC7fs4"), datetime: Date.from(dateString: "2015-08-30T14:43:29.000+09:00"))
        let cafeDoc2 = DKDocument(title: "L.A. 2017 1v1 Tournament Match 3] PowerOfEvil vs Jisu", contents: "PowerOfEvil - 오리아나 BAN - 렝가, 올라프, 나서스 <b>Jisu</b> - 판테온 BAN - 카시오페아, 라이즈, 루시안 1v1 Tournament Round of 16 Faker 1 VVvert 0 Bjergsen 1 FoFo...", url: URL(string: "http://cafe.daum.net/dotax/O63C/14007"), cafeName: "도탁스 (DOTAX)", blogName: nil, thumbnailURL: URL(string: "https://search1.kakaocdn.net/thumb/P100x100/?fname=https%3A%2F%2Fsearch2.kakaocdn.net%2Fargon%2F130x130_85_c%2F9PEO0S1yaHt"), datetime: Date.from(dateString: "2017-12-08T14:57:41.000+09:00"))
    }
}
