//
//  SearchListCellDataDummy.swift
//  search_blog_and_cafeTests
//
//  Created by Bo-Young PARK on 2020/02/25.
//  Copyright © 2020 Boyoung Park. All rights reserved.
//

import Foundation

@testable import search_blog_and_cafe

struct SearchListCellDataListDummy {
    let cellDataList0 = [SearchListCellDataDummy().cellData0, SearchListCellDataDummy().cellData1, SearchListCellDataDummy().cellData2, SearchListCellDataDummy().cellData3, SearchListCellDataDummy().cellData4]
    let cellDataList1 = [SearchListCellDataDummy().cellData0, SearchListCellDataDummy().cellData1, SearchListCellDataDummy().cellData2, SearchListCellDataDummy().cellData3, SearchListCellDataDummy().cellData4, SearchListCellDataDummy().cellData5, SearchListCellDataDummy().cellData6, SearchListCellDataDummy().cellData7, SearchListCellDataDummy().cellData8, SearchListCellDataDummy().cellData9, SearchListCellDataDummy().cellData10, SearchListCellDataDummy().cellData11, SearchListCellDataDummy().cellData12, SearchListCellDataDummy().cellData13, SearchListCellDataDummy().cellData14, SearchListCellDataDummy().cellData15, SearchListCellDataDummy().cellData16, SearchListCellDataDummy().cellData17, SearchListCellDataDummy().cellData18, SearchListCellDataDummy().cellData19, SearchListCellDataDummy().cellData20, SearchListCellDataDummy().cellData21, SearchListCellDataDummy().cellData22, SearchListCellDataDummy().cellData23, SearchListCellDataDummy().cellData24, SearchListCellDataDummy().cellData25, SearchListCellDataDummy().cellData26, SearchListCellDataDummy().cellData27]
}

extension SearchListCellDataListDummy {
    struct SearchListCellDataDummy {
        let cellData0 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/6bnWYu0NiYO"), type: .blog, name: "뉴스필터", title: "[수원 코로나 사망자] 음성????", contents: "수원에 코로나 사망자가 나왔다고 깜짝 놀랐는데요 확인해본결과 결국 <b>코로나</b>는 음성판정이 나왔고 지병때문에 사망한듯 합니다. 다행이네요 근래 중국을 방문해 신종 <b>코로나</b>바이러스 감염증이 의심된 40대 남성이 숨진 채 발견 됐습니다. 13일 수원중부경찰서에 말에 의하면 이날 오전 8시 13분께 수원시 팔달구 팔달로...", datetime: Date.from(dateString: "2020-02-13T14:47:00.000+09:00"), url: URL(string: "http://filternews.tistory.com/1377"), didURLLinkTapped: false)
        let cellData1 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/HxpSZ5XdJzd"), type: .blog, name: "issue", title: "코로나 바이러스", contents: "바이러스 정리 신종 바이러스 우한폐렴 상황 정부대처 신종 코로나 바이러스", datetime: Date.from(dateString: "2020-02-22T00:08:00.000+09:00"), url: URL(string: "http://day-issue.tistory.com/42"), didURLLinkTapped: false)
        let cellData2 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/6bnWYu0NiYO"), type: .blog, name: "뉴스필터", title: "[수원 코로나 사망자] 음성????", contents: "수원에 코로나 사망자가 나왔다고 깜짝 놀랐는데요 확인해본결과 결국 <b>코로나</b>는 음성판정이 나왔고 지병때문에 사망한듯 합니다. 다행이네요 근래 중국을 방문해 신종 <b>코로나</b>바이러스 감염증이 의심된 40대 남성이 숨진 채 발견 됐습니다. 13일 수원중부경찰서에 말에 의하면 이날 오전 8시 13분께 수원시 팔달구 팔달로...", datetime: Date.from(dateString: "2020-02-13T14:47:00.000+09:00"), url: URL(string: "http://filternews.tistory.com/1377"), didURLLinkTapped: false)
        let cellData3 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/HxpSZ5XdJzd"), type: .blog, name: "issue", title: "코로나 바이러스", contents: "바이러스 정리 신종 바이러스 우한폐렴 상황 정부대처 신종 코로나 바이러스", datetime: Date.from(dateString: "2020-02-22T00:08:00.000+09:00"), url: URL(string: "http://day-issue.tistory.com/42"), didURLLinkTapped: false)
        let cellData4 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/6bnWYu0NiYO"), type: .blog, name: "뉴스필터", title: "[수원 코로나 사망자] 음성????", contents: "수원에 코로나 사망자가 나왔다고 깜짝 놀랐는데요 확인해본결과 결국 <b>코로나</b>는 음성판정이 나왔고 지병때문에 사망한듯 합니다. 다행이네요 근래 중국을 방문해 신종 <b>코로나</b>바이러스 감염증이 의심된 40대 남성이 숨진 채 발견 됐습니다. 13일 수원중부경찰서에 말에 의하면 이날 오전 8시 13분께 수원시 팔달구 팔달로...", datetime: Date.from(dateString: "2020-02-13T14:47:00.000+09:00"), url: URL(string: "http://filternews.tistory.com/1377"), didURLLinkTapped: false)
        let cellData5 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/HxpSZ5XdJzd"), type: .blog, name: "issue", title: "코로나 바이러스", contents: "바이러스 정리 신종 바이러스 우한폐렴 상황 정부대처 신종 코로나 바이러스", datetime: Date.from(dateString: "2020-02-22T00:08:00.000+09:00"), url: URL(string: "http://day-issue.tistory.com/42"), didURLLinkTapped: false)
        let cellData6 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/6bnWYu0NiYO"), type: .blog, name: "뉴스필터", title: "[수원 코로나 사망자] 음성????", contents: "수원에 코로나 사망자가 나왔다고 깜짝 놀랐는데요 확인해본결과 결국 <b>코로나</b>는 음성판정이 나왔고 지병때문에 사망한듯 합니다. 다행이네요 근래 중국을 방문해 신종 <b>코로나</b>바이러스 감염증이 의심된 40대 남성이 숨진 채 발견 됐습니다. 13일 수원중부경찰서에 말에 의하면 이날 오전 8시 13분께 수원시 팔달구 팔달로...", datetime: Date.from(dateString: "2020-02-13T14:47:00.000+09:00"), url: URL(string: "http://filternews.tistory.com/1377"), didURLLinkTapped: false)
        let cellData7 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/HxpSZ5XdJzd"), type: .blog, name: "issue", title: "코로나 바이러스", contents: "바이러스 정리 신종 바이러스 우한폐렴 상황 정부대처 신종 코로나 바이러스", datetime: Date.from(dateString: "2020-02-22T00:08:00.000+09:00"), url: URL(string: "http://day-issue.tistory.com/42"), didURLLinkTapped: false)
        let cellData8 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/6bnWYu0NiYO"), type: .blog, name: "뉴스필터", title: "[수원 코로나 사망자] 음성????", contents: "수원에 코로나 사망자가 나왔다고 깜짝 놀랐는데요 확인해본결과 결국 <b>코로나</b>는 음성판정이 나왔고 지병때문에 사망한듯 합니다. 다행이네요 근래 중국을 방문해 신종 <b>코로나</b>바이러스 감염증이 의심된 40대 남성이 숨진 채 발견 됐습니다. 13일 수원중부경찰서에 말에 의하면 이날 오전 8시 13분께 수원시 팔달구 팔달로...", datetime: Date.from(dateString: "2020-02-13T14:47:00.000+09:00"), url: URL(string: "http://filternews.tistory.com/1377"), didURLLinkTapped: false)
        let cellData9 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/HxpSZ5XdJzd"), type: .blog, name: "issue", title: "코로나 바이러스", contents: "바이러스 정리 신종 바이러스 우한폐렴 상황 정부대처 신종 코로나 바이러스", datetime: Date.from(dateString: "2020-02-22T00:08:00.000+09:00"), url: URL(string: "http://day-issue.tistory.com/42"), didURLLinkTapped: false)
        let cellData10 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/6bnWYu0NiYO"), type: .blog, name: "뉴스필터", title: "[수원 코로나 사망자] 음성????", contents: "수원에 코로나 사망자가 나왔다고 깜짝 놀랐는데요 확인해본결과 결국 <b>코로나</b>는 음성판정이 나왔고 지병때문에 사망한듯 합니다. 다행이네요 근래 중국을 방문해 신종 <b>코로나</b>바이러스 감염증이 의심된 40대 남성이 숨진 채 발견 됐습니다. 13일 수원중부경찰서에 말에 의하면 이날 오전 8시 13분께 수원시 팔달구 팔달로...", datetime: Date.from(dateString: "2020-02-13T14:47:00.000+09:00"), url: URL(string: "http://filternews.tistory.com/1377"), didURLLinkTapped: false)
        let cellData11 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/HxpSZ5XdJzd"), type: .blog, name: "issue", title: "코로나 바이러스", contents: "바이러스 정리 신종 바이러스 우한폐렴 상황 정부대처 신종 코로나 바이러스", datetime: Date.from(dateString: "2020-02-22T00:08:00.000+09:00"), url: URL(string: "http://day-issue.tistory.com/42"), didURLLinkTapped: false)
        let cellData12 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/6bnWYu0NiYO"), type: .blog, name: "뉴스필터", title: "[수원 코로나 사망자] 음성????", contents: "수원에 코로나 사망자가 나왔다고 깜짝 놀랐는데요 확인해본결과 결국 <b>코로나</b>는 음성판정이 나왔고 지병때문에 사망한듯 합니다. 다행이네요 근래 중국을 방문해 신종 <b>코로나</b>바이러스 감염증이 의심된 40대 남성이 숨진 채 발견 됐습니다. 13일 수원중부경찰서에 말에 의하면 이날 오전 8시 13분께 수원시 팔달구 팔달로...", datetime: Date.from(dateString: "2020-02-13T14:47:00.000+09:00"), url: URL(string: "http://filternews.tistory.com/1377"), didURLLinkTapped: false)
        let cellData13 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/HxpSZ5XdJzd"), type: .blog, name: "issue", title: "코로나 바이러스", contents: "바이러스 정리 신종 바이러스 우한폐렴 상황 정부대처 신종 코로나 바이러스", datetime: Date.from(dateString: "2020-02-22T00:08:00.000+09:00"), url: URL(string: "http://day-issue.tistory.com/42"), didURLLinkTapped: false)
        let cellData14 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/6bnWYu0NiYO"), type: .blog, name: "뉴스필터", title: "[수원 코로나 사망자] 음성????", contents: "수원에 코로나 사망자가 나왔다고 깜짝 놀랐는데요 확인해본결과 결국 <b>코로나</b>는 음성판정이 나왔고 지병때문에 사망한듯 합니다. 다행이네요 근래 중국을 방문해 신종 <b>코로나</b>바이러스 감염증이 의심된 40대 남성이 숨진 채 발견 됐습니다. 13일 수원중부경찰서에 말에 의하면 이날 오전 8시 13분께 수원시 팔달구 팔달로...", datetime: Date.from(dateString: "2020-02-13T14:47:00.000+09:00"), url: URL(string: "http://filternews.tistory.com/1377"), didURLLinkTapped: false)
        let cellData15 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/HxpSZ5XdJzd"), type: .blog, name: "issue", title: "코로나 바이러스", contents: "바이러스 정리 신종 바이러스 우한폐렴 상황 정부대처 신종 코로나 바이러스", datetime: Date.from(dateString: "2020-02-22T00:08:00.000+09:00"), url: URL(string: "http://day-issue.tistory.com/42"), didURLLinkTapped: false)
        let cellData16 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/6bnWYu0NiYO"), type: .blog, name: "뉴스필터", title: "[수원 코로나 사망자] 음성????", contents: "수원에 코로나 사망자가 나왔다고 깜짝 놀랐는데요 확인해본결과 결국 <b>코로나</b>는 음성판정이 나왔고 지병때문에 사망한듯 합니다. 다행이네요 근래 중국을 방문해 신종 <b>코로나</b>바이러스 감염증이 의심된 40대 남성이 숨진 채 발견 됐습니다. 13일 수원중부경찰서에 말에 의하면 이날 오전 8시 13분께 수원시 팔달구 팔달로...", datetime: Date.from(dateString: "2020-02-13T14:47:00.000+09:00"), url: URL(string: "http://filternews.tistory.com/1377"), didURLLinkTapped: false)
        let cellData17 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/HxpSZ5XdJzd"), type: .blog, name: "issue", title: "코로나 바이러스", contents: "바이러스 정리 신종 바이러스 우한폐렴 상황 정부대처 신종 코로나 바이러스", datetime: Date.from(dateString: "2020-02-22T00:08:00.000+09:00"), url: URL(string: "http://day-issue.tistory.com/42"), didURLLinkTapped: false)
        let cellData18 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/6bnWYu0NiYO"), type: .blog, name: "뉴스필터", title: "[수원 코로나 사망자] 음성????", contents: "수원에 코로나 사망자가 나왔다고 깜짝 놀랐는데요 확인해본결과 결국 <b>코로나</b>는 음성판정이 나왔고 지병때문에 사망한듯 합니다. 다행이네요 근래 중국을 방문해 신종 <b>코로나</b>바이러스 감염증이 의심된 40대 남성이 숨진 채 발견 됐습니다. 13일 수원중부경찰서에 말에 의하면 이날 오전 8시 13분께 수원시 팔달구 팔달로...", datetime: Date.from(dateString: "2020-02-13T14:47:00.000+09:00"), url: URL(string: "http://filternews.tistory.com/1377"), didURLLinkTapped: false)
        let cellData19 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/HxpSZ5XdJzd"), type: .blog, name: "issue", title: "코로나 바이러스", contents: "바이러스 정리 신종 바이러스 우한폐렴 상황 정부대처 신종 코로나 바이러스", datetime: Date.from(dateString: "2020-02-22T00:08:00.000+09:00"), url: URL(string: "http://day-issue.tistory.com/42"), didURLLinkTapped: false)
        let cellData20 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/6bnWYu0NiYO"), type: .blog, name: "뉴스필터", title: "[수원 코로나 사망자] 음성????", contents: "수원에 코로나 사망자가 나왔다고 깜짝 놀랐는데요 확인해본결과 결국 <b>코로나</b>는 음성판정이 나왔고 지병때문에 사망한듯 합니다. 다행이네요 근래 중국을 방문해 신종 <b>코로나</b>바이러스 감염증이 의심된 40대 남성이 숨진 채 발견 됐습니다. 13일 수원중부경찰서에 말에 의하면 이날 오전 8시 13분께 수원시 팔달구 팔달로...", datetime: Date.from(dateString: "2020-02-13T14:47:00.000+09:00"), url: URL(string: "http://filternews.tistory.com/1377"), didURLLinkTapped: false)
        let cellData21 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/HxpSZ5XdJzd"), type: .blog, name: "issue", title: "코로나 바이러스", contents: "바이러스 정리 신종 바이러스 우한폐렴 상황 정부대처 신종 코로나 바이러스", datetime: Date.from(dateString: "2020-02-22T00:08:00.000+09:00"), url: URL(string: "http://day-issue.tistory.com/42"), didURLLinkTapped: false)
        let cellData22 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/6bnWYu0NiYO"), type: .blog, name: "뉴스필터", title: "[수원 코로나 사망자] 음성????", contents: "수원에 코로나 사망자가 나왔다고 깜짝 놀랐는데요 확인해본결과 결국 <b>코로나</b>는 음성판정이 나왔고 지병때문에 사망한듯 합니다. 다행이네요 근래 중국을 방문해 신종 <b>코로나</b>바이러스 감염증이 의심된 40대 남성이 숨진 채 발견 됐습니다. 13일 수원중부경찰서에 말에 의하면 이날 오전 8시 13분께 수원시 팔달구 팔달로...", datetime: Date.from(dateString: "2020-02-13T14:47:00.000+09:00"), url: URL(string: "http://filternews.tistory.com/1377"), didURLLinkTapped: false)
        let cellData23 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/HxpSZ5XdJzd"), type: .blog, name: "issue", title: "코로나 바이러스", contents: "바이러스 정리 신종 바이러스 우한폐렴 상황 정부대처 신종 코로나 바이러스", datetime: Date.from(dateString: "2020-02-22T00:08:00.000+09:00"), url: URL(string: "http://day-issue.tistory.com/42"), didURLLinkTapped: false)
        let cellData24 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/6bnWYu0NiYO"), type: .blog, name: "뉴스필터", title: "[수원 코로나 사망자] 음성????", contents: "수원에 코로나 사망자가 나왔다고 깜짝 놀랐는데요 확인해본결과 결국 <b>코로나</b>는 음성판정이 나왔고 지병때문에 사망한듯 합니다. 다행이네요 근래 중국을 방문해 신종 <b>코로나</b>바이러스 감염증이 의심된 40대 남성이 숨진 채 발견 됐습니다. 13일 수원중부경찰서에 말에 의하면 이날 오전 8시 13분께 수원시 팔달구 팔달로...", datetime: Date.from(dateString: "2020-02-13T14:47:00.000+09:00"), url: URL(string: "http://filternews.tistory.com/1377"), didURLLinkTapped: false)
        let cellData25 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/HxpSZ5XdJzd"), type: .blog, name: "issue", title: "코로나 바이러스", contents: "바이러스 정리 신종 바이러스 우한폐렴 상황 정부대처 신종 코로나 바이러스", datetime: Date.from(dateString: "2020-02-22T00:08:00.000+09:00"), url: URL(string: "http://day-issue.tistory.com/42"), didURLLinkTapped: false)
        let cellData26 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/6bnWYu0NiYO"), type: .blog, name: "뉴스필터", title: "[수원 코로나 사망자] 음성????", contents: "수원에 코로나 사망자가 나왔다고 깜짝 놀랐는데요 확인해본결과 결국 <b>코로나</b>는 음성판정이 나왔고 지병때문에 사망한듯 합니다. 다행이네요 근래 중국을 방문해 신종 <b>코로나</b>바이러스 감염증이 의심된 40대 남성이 숨진 채 발견 됐습니다. 13일 수원중부경찰서에 말에 의하면 이날 오전 8시 13분께 수원시 팔달구 팔달로...", datetime: Date.from(dateString: "2020-02-13T14:47:00.000+09:00"), url: URL(string: "http://filternews.tistory.com/1377"), didURLLinkTapped: false)
        let cellData27 = SearchListCellData(thumbnailURL: URL(string: "https://search2.kakaocdn.net/argon/130x130_85_c/HxpSZ5XdJzd"), type: .blog, name: "issue", title: "코로나 바이러스", contents: "바이러스 정리 신종 바이러스 우한폐렴 상황 정부대처 신종 코로나 바이러스", datetime: Date.from(dateString: "2020-02-22T00:08:00.000+09:00"), url: URL(string: "http://day-issue.tistory.com/42"), didURLLinkTapped: false)
    }
}
